### ISSUE TITLE
summary metrics like AP

### ISSUE THREAD

**Issue by baoxiaoyi** [Tanveer81/GRAttVIS#2]
Great work!
One question for the code: I can't find the metrics output like AP AP50 AP100...
My outputfile is like: output/inference/results.json&instances_predictions.pth
Where can I find the metric output in your paper?

**Comment by Tanveer81** [comment]
The ground truth for evaluation set is not publicly available. You have to zip the json file and upload the zip file to the competition server for the final metrics. Please refer to the following code as a reference. 
[Upload predictions to server from InstanceFormer.](https://github.com/rajatkoner08/InstanceFormer/blob/main/util/server_process.py)

**Comment by baoxiaoyi** [comment]
Thanks.
