### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by wengkai0** [Tanveer81/GRAttVIS#3]
Hi Sir,

Thanks for your excellent work! I met a problem after following the installation process and dataset preparation:  when I run the code: it shows that 
ImportError: cannot import name 'datasets' from partially initialized module 'mask2former.data' (most likely due to a circular import)

Could you find out the possible problems?

Thanks

**Comment by rajatkoner08** [comment]
We didn't face it. Can you give a stack trace?

**Comment by wengkai0** [comment]
Hi, thanks for your reply, 

I installed the environment follow your instruction and try to run the following code:

python train_net_grattvis.py --num-gpus 2 --config-file configs/grattvis/youtubevis_2019/grattvis_R50_bs8.yaml
Traceback (most recent call last):
  File "train_net_grattvis.py", line 42, in <module>
    from mask2former import add_maskformer2_config
  File "/data/project/GRAttVIS/mask2former/__init__.py", line 2, in <module>
    from . import data  # register all new datasets
  File "/data/project/GRAttVIS/mask2former/data/__init__.py", line 2, in <module>
    from . import datasets
ImportError: cannot import name 'datasets' from partially initialized module 'mask2former.data' (most likely due to a circular import) (/data/project/GRAttVIS/mask2former/data/__init__.py)

Could you please give any clues about the errors?

Kindly Regards

**Comment by Tanveer81** [comment]
This is solved in the latest [commit](https://github.com/Tanveer81/GRAttVIS/commit/5f49e7f9d901b594f7d06e2bbc4c3445836aae24).

The .gitignore removed **datasets** folders from _/mask2former/data_ and _/vita/data_. 

Thanks for pointing it out.

**Comment by wengkai0** [comment]
Hi, 

Thanks much for your prompt reply and solution.

I will have a try
