### ISSUE TITLE
A question about the code

### ISSUE THREAD

**Issue by JinYoon002** [Tanveer81/GRAttVIS#4]
Dear authors,

I met this problem when running the code, could you please check?

File "/home/anaconda/envs/vita/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'Genvis' found in 'META_ARCH' registry!"

**Comment by Tanveer81** [comment]
Can you provide the command you ran and the stack trace?

**Comment by Tanveer81** [comment]
Thanks for pointing out the bug. The latest [commit](https://github.com/Tanveer81/GRAttVIS/commit/16971d9539a41fa5c33e3fa98b8bc2b486c574e8) fixes the issue.

**Comment by JinYoon002** [comment]
Thank you!
